# Generated by Django 5.0.7 on 2024-08-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieID', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('comment_text', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
