# Generated by Django 5.0.7 on 2024-08-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('imdb_id', models.CharField(max_length=50, unique=True)),
                ('poster_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='movieID',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_name',
        ),
        migrations.AddField(
            model_name='comment',
            name='nickname',
            field=models.TextField(default='bora'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(),
        ),
    ]
