# Generated by Django 5.0.7 on 2024-08-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0003_remove_comment_nickname_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='movie_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
