# Generated by Django 5.0.7 on 2024-08-10 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0004_comment_created_at_comment_movie_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='movie_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mywebsite.movie'),
            preserve_default=False,
        ),
    ]
