# Generated by Django 5.0.7 on 2024-08-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0005_remove_comment_movie_id_comment_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='movie',
        ),
    ]
