# Generated by Django 5.0.7 on 2024-08-10 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0006_remove_comment_created_at_remove_comment_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
