# Generated by Django 5.0.7 on 2024-08-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0008_movie'),
    ]

    operations = [
        migrations.AddField(
        model_name='comment',
        name='movie_id',
        field=models.ForeignKey(to='mywebsite.Movie', on_delete=models.CASCADE),
)
    ]
