# Generated by Django 5.0.7 on 2024-08-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0010_remove_comment_movie_id_comment_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='movie',
        ),
        migrations.AddField(
            model_name='comment',
            name='movie_id',
            field=models.IntegerField(default=0),
        ),
    ]
